version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    container_name: plain-express-typescript
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 23000:3000
